# Generated by Django 4.1.1 on 2022-11-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='User',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='User',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
