# Generated by Django 4.1.2 on 2022-11-12 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='User',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
