# Generated by Django 4.1.1 on 2022-11-14 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0005_customer_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='User',
            new_name='user',
        ),
    ]
