# Generated by Django 4.1.1 on 2022-11-14 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0006_rename_user_cart_user_rename_user_customer_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Product',
            new_name='product',
        ),
    ]
