# Generated by Django 4.1.2 on 2022-11-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0008_alter_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Customer',
            new_name='customer',
        ),
    ]
