# Generated by Django 4.1.2 on 2022-11-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0009_rename_customer_orderplaced_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('On the way', 'On the way'), ('Reached the destination', 'Reached the destination'), ('Cancel', 'Cancel')], default='pending', max_length=100),
        ),
    ]
