# Generated by Django 4.1.2 on 2022-11-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0010_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On the way', 'On the way'), ('Reached the destination', 'Reached the destination'), ('Cancel', 'Cancel')], default='Pending', max_length=100),
        ),
    ]
